apiVersion: apps/v1
kind: Deployment
metadata:
  name: exposure-scanner
  labels:
    app: exposure-scanner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exposure-scanner
  template:
    metadata:
      labels:
        app: exposure-scanner
    spec:
      # Your exercise requirement: app runs with cluster-admin via default SA binding
      serviceAccountName: default
      containers:
        - name: exposure-scanner
          # IMPORTANT: Binary Auth likes digests, not tags. We'll set the digest via kustomize.
          image: us-east1-docker.pkg.dev/clgcporg10-178/wiz-repo/exposure-scanner@sha256:REPLACE_ME
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URI
              value: "mongodb://admin:VeryStrongPass123%21@10.20.0.3:27017/admin?authSource=admin"