apiVersion: apps/v1
kind: Deployment
metadata:
  name: exposure-scanner
  labels:
    app: exposure-scanner
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exposure-scanner
  template:
    metadata:
      labels:
        app: exposure-scanner
    spec:
      containers:
        - name: exposure-scanner
          image: exposure-scanner
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: MONGO_URI
              value: "mongodb://admin:VeryStrongPass123%21@10.20.0.3:27017/admin?authSource=admin"
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 15
            periodSeconds: 20